// src/tarot/cards.ts
export interface TarotCard {
  name: string;
  persianName: string;
}

export const tarotCards: TarotCard[] = [
  // Major Arcana
  { name: "The Fool", persianName: "ابله" },
  { name: "The Magician", persianName: "جادوگر" },
  { name: "The High Priestess", persianName: "راهبه اعظم" },
  { name: "The Empress", persianName: "امپراتریس" },
  { name: "The Emperor", persianName: "امپراتور" },
  { name: "The Hierophant", persianName: "کاهن اعظم" },
  { name: "The Lovers", persianName: "عشاق" },
  { name: "The Chariot", persianName: "ارابه" },
  { name: "Strength", persianName: "قدرت" },
  { name: "The Hermit", persianName: "زاهد" },
  { name: "Wheel of Fortune", persianName: "چرخ اقبال" },
  { name: "Justice", persianName: "عدالت" },
  { name: "The Hanged Man", persianName: "مرد آویخته" },
  { name: "Death", persianName: "مرگ" },
  { name: "Temperance", persianName: "اعتدال" },
  { name: "The Devil", persianName: "شیطان" },
  { name: "The Tower", persianName: "برج" },
  { name: "The Star", persianName: "ستاره" },
  { name: "The Moon", persianName: "ماه" },
  { name: "The Sun", persianName: "خورشید" },
  { name: "Judgement", persianName: "رستاخیز" },
  { name: "The World", persianName: "جهان" },

  // Wands (عصا / چوب‌دست)
  { name: "Ace of Wands", persianName: "آس عصا" },
  { name: "Two of Wands", persianName: "دو عصا" },
  { name: "Three of Wands", persianName: "سه عصا" },
  { name: "Four of Wands", persianName: "چهار عصا" },
  { name: "Five of Wands", persianName: "پنج عصا" },
  { name: "Six of Wands", persianName: "شش عصا" },
  { name: "Seven of Wands", persianName: "هفت عصا" },
  { name: "Eight of Wands", persianName: "هشت عصا" },
  { name: "Nine of Wands", persianName: "نه عصا" },
  { name: "Ten of Wands", persianName: "ده عصا" },
  { name: "Page of Wands", persianName: "صفحه عصا" },
  { name: "Knight of Wands", persianName: "شوالیه عصا" },
  { name: "Queen of Wands", persianName: "ملکه عصا" },
  { name: "King of Wands", persianName: "شاه عصا" },

  // Cups (جام)
  { name: "Ace of Cups", persianName: "آس جام" },
  { name: "Two of Cups", persianName: "دو جام" },
  { name: "Three of Cups", persianName: "سه جام" },
  { name: "Four of Cups", persianName: "چهار جام" },
  { name: "Five of Cups", persianName: "پنج جام" },
  { name: "Six of Cups", persianName: "شش جام" },
  { name: "Seven of Cups", persianName: "هفت جام" },
  { name: "Eight of Cups", persianName: "هشت جام" },
  { name: "Nine of Cups", persianName: "نه جام" },
  { name: "Ten of Cups", persianName: "ده جام" },
  { name: "Page of Cups", persianName: "صفحه جام" },
  { name: "Knight of Cups", persianName: "شوالیه جام" },
  { name: "Queen of Cups", persianName: "ملکه جام" },
  { name: "King of Cups", persianName: "شاه جام" },

  // Swords (شمشیر)
  { name: "Ace of Swords", persianName: "آس شمشیر" },
  { name: "Two of Swords", persianName: "دو شمشیر" },
  { name: "Three of Swords", persianName: "سه شمشیر" },
  { name: "Four of Swords", persianName: "چهار شمشیر" },
  { name: "Five of Swords", persianName: "پنج شمشیر" },
  { name: "Six of Swords", persianName: "شش شمشیر" },
  { name: "Seven of Swords", persianName: "هفت شمشیر" },
  { name: "Eight of Swords", persianName: "هشت شمشیر" },
  { name: "Nine of Swords", persianName: "نه شمشیر" },
  { name: "Ten of Swords", persianName: "ده شمشیر" },
  { name: "Page of Swords", persianName: "صفحه شمشیر" },
  { name: "Knight of Swords", persianName: "شوالیه شمشیر" },
  { name: "Queen of Swords", persianName: "ملکه شمشیر" },
  { name: "King of Swords", persianName: "شاه شمشیر" },

  // Pentacles (سکه / پنتاکل)
  { name: "Ace of Pentacles", persianName: "آس سکه" },
  { name: "Two of Pentacles", persianName: "دو سکه" },
  { name: "Three of Pentacles", persianName: "سه سکه" },
  { name: "Four of Pentacles", persianName: "چهار سکه" },
  { name: "Five of Pentacles", persianName: "پنج سکه" },
  { name: "Six of Pentacles", persianName: "شش سکه" },
  { name: "Seven of Pentacles", persianName: "هفت سکه" },
  { name: "Eight of Pentacles", persianName: "هشت سکه" },
  { name: "Nine of Pentacles", persianName: "نه سکه" },
  { name: "Ten of Pentacles", persianName: "ده سکه" },
  { name: "Page of Pentacles", persianName: "صفحه سکه" },
  { name: "Knight of Pentacles", persianName: "شوالیه سکه" },
  { name: "Queen of Pentacles", persianName: "ملکه سکه" },
  { name: "King of Pentacles", persianName: "شاه سکه" },
];